#
# .travis.yml
#

language: "node_js"

node_js:
  - "stable"
  - "4.2" # Argon
  - "0.12"

install:
  - "npm install"
  - "npm install eslint babel-eslint natronjs/eslint-config-natron"
  - "npm --prefix build install"

script:
  - "node_modules/.bin/eslint ."
